import { spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, rm } from "node:fs/promises";
import path from "node:path";
import { validateResPath } from "./paths.mjs";
import { terminateProcessTree } from "./process-utils.mjs";

function stripAnsi(value) {
  return value.replace(/\u001B\[[0-?]*[ -/]*[@-~]/g, "");
}

function normalizeOutput(value) {
  return stripAnsi(value).replace(/\r\n?/g, "\n");
}

function limitOutput(value, maxCharacters) {
  const clean = normalizeOutput(value).trim();
  if (clean.length <= maxCharacters) return clean;
  return `[output truncated; last ${maxCharacters} characters]\n${clean.slice(-maxCharacters)}`;
}

function numberFrom(text, patterns) {
  for (const pattern of patterns) {
    const match = text.match(pattern);
    if (match) return Number.parseInt(match[1], 10);
  }
  return null;
}

function attributeFrom(tag, name) {
  const match = tag.match(new RegExp(`\\b${name}\\s*=\\s*["'](\\d+)["']`, "i"));
  return match ? Number.parseInt(match[1], 10) : null;
}

function textAttributeFrom(tag, name) {
  const match = tag.match(new RegExp(`\\b${name}\\s*=\\s*["']([^"']*)["']`, "i"));
  return match ? decodeXmlEntities(match[1]) : null;
}

function decodeXmlEntities(value) {
  return value
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&")
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number.parseInt(code, 10)))
    .replace(/&#x([0-9a-f]+);/gi, (_, code) => String.fromCodePoint(Number.parseInt(code, 16)));
}

function tagText(value) {
  return decodeXmlEntities(value.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim());
}

function fatalMessagesFromOutput(combined) {
  // Generic "SCRIPT ERROR" is intentionally excluded. GUT error tracking can
  // capture expected engine/script errors while the related test still passes.
  const fatalPatterns = [
    /Some GUT class_names have not been imported/i,
    /Missing class_names/i,
    /Parse Error/i,
    /Could not resolve class/i,
    /Could not load script/i,
    /No loader found for resource/i,
    /Failed loading (?:scene|script)/i,
    /Cannot open project/i,
    /gut_cmdln\.gd.*(?:not found|could not)/i,
    /No tests found/i,
  ];
  return fatalPatterns.filter((pattern) => pattern.test(combined)).map((pattern) => pattern.source);
}

/** Parse the JUnit XML generated by GUT's -gjunit_xml_file option. */
export function parseGutJunitXml(xml, exitCode = 0, timedOut = false) {
  const clean = String(xml || "").trim();
  if (!clean.startsWith("<?xml") && !clean.startsWith("<testsuites")) {
    throw new Error("GUT JUnit XML is missing or malformed: <testsuites> was not found.");
  }
  const rootTag = clean.match(/<testsuites\b[^>]*>/i)?.[0];
  if (!rootTag) throw new Error("GUT JUnit XML is malformed: <testsuites> was not found.");

  const suiteTags = [...clean.matchAll(/<testsuite\b[^>]*>/gi)].map((match) => match[0]);
  const testcaseBlocks = [...clean.matchAll(/<testcase\b([^>]*)>([\s\S]*?)<\/testcase>|<testcase\b([^>]*)\/>/gi)];
  const failureBlocks = [...clean.matchAll(/<(failure|error)\b([^>]*)>([\s\S]*?)<\/\1>/gi)];
  const sumSuiteAttribute = (name) => suiteTags.reduce((total, tag) => total + (attributeFrom(tag, name) ?? 0), 0);

  const tests = attributeFrom(rootTag, "tests") ?? sumSuiteAttribute("tests");
  const failingTests = attributeFrom(rootTag, "failures") ?? sumSuiteAttribute("failures");
  const errors = attributeFrom(rootTag, "errors") ?? Math.max(sumSuiteAttribute("errors"), failureBlocks.filter((m) => m[1].toLowerCase() === "error").length);
  const pendingTests = attributeFrom(rootTag, "skipped") ?? sumSuiteAttribute("skipped");
  const scripts = suiteTags.filter((tag) => (attributeFrom(tag, "tests") ?? 0) > 0).length;

  let asserts = 0;
  let passingFromCases = 0;
  let failingFromCases = 0;
  let pendingFromCases = 0;
  for (const match of testcaseBlocks) {
    const attrs = `<testcase ${match[1] || match[3] || ""}>`;
    asserts += attributeFrom(attrs, "assertions") ?? 0;
    const status = (textAttributeFrom(attrs, "status") || "").toLowerCase();
    if (status === "pass") passingFromCases += 1;
    else if (status === "fail" || status === "error") failingFromCases += 1;
    else if (status === "pending" || status === "skipped") pendingFromCases += 1;
  }

  const effectiveFailing = Math.max(failingTests, failingFromCases);
  const effectivePending = Math.max(pendingTests, pendingFromCases);
  const passingTests = passingFromCases > 0 ? passingFromCases : Math.max(0, tests - effectiveFailing - errors - effectivePending);
  const failures = failureBlocks.map((match) => ({
    type: match[1].toLowerCase(),
    message: textAttributeFrom(`<${match[1]} ${match[2] || ""}>`, "message"),
    details: tagText(match[3] || ""),
  }));

  return {
    passed: exitCode === 0 && !timedOut && tests > 0 && asserts > 0 && effectiveFailing === 0 && errors === 0,
    counts: {
      scripts,
      tests,
      passing_tests: passingTests,
      failing_tests: effectiveFailing,
      pending_tests: effectivePending,
      asserts,
      errors,
      warnings: null,
    },
    failure: failures.length > 0 ? failures : null,
    fatal_patterns: [],
    result_source: "junit_xml",
    parser_warning: null,
  };
}

/** Text parser retained as a compatibility fallback when JUnit XML is unavailable. */
export function parseGutOutput(stdout, stderr, exitCode, timedOut = false) {
  const combined = normalizeOutput(`${stdout}\n${stderr}`);
  const scripts = numberFrom(combined, [/(?:^|\n)\s*Scripts?\s*:\s*(\d+)/i, /(?:^|\n)\s*Scripts?\s+(\d+)\s*$/im]);
  let tests = numberFrom(combined, [/(?:^|\n)\s*Tests?\s*:\s*(\d+)/i, /(?:^|\n)\s*Tests?\s+(\d+)\s*$/im, /(?:^|\n)\s*Total Tests?\s*:\s*(\d+)/i]);
  let passingTests = numberFrom(combined, [/Passing Tests?\s*:\s*(\d+)/i, /Tests? Passed\s*:\s*(\d+)/i, /(?:^|\n)\s*Passing\s*:\s*(\d+)/i]);
  const ratio = combined.match(/\b(\d+)\s*\/\s*(\d+)\s+(?:tests?\s+)?pass(?:ed|ing)\b/i);
  if (ratio) {
    passingTests ??= Number.parseInt(ratio[1], 10);
    tests ??= Number.parseInt(ratio[2], 10);
  }
  const failingTests = numberFrom(combined, [/Failing Tests?\s*:\s*(\d+)/i, /Tests? Failed\s*:\s*(\d+)/i, /(?:^|\n)\s*Failing\s*:\s*(\d+)/i, /(?:^|\n)\s*Failures?\s*:\s*(\d+)/i]) ?? 0;
  const pendingTests = numberFrom(combined, [/Pending Tests?\s*:\s*(\d+)/i, /(?:^|\n)\s*Pending\s*:\s*(\d+)/i, /(?:^|\n)\s*Skipped\s*:\s*(\d+)/i]) ?? 0;
  const asserts = numberFrom(combined, [/(?:^|\n)\s*Asserts?\s*:\s*(\d+)/i, /\b(\d+)\s+asserts?\b/i]);
  const errorsReported = numberFrom(combined, [/(?:^|\n)\s*Errors?\s*:\s*(\d+)/i, /(?:^|\n)\s*Errors?\s+(\d+)\s*$/im]) ?? 0;
  const warnings = numberFrom(combined, [/(?:^|\n)\s*Warnings?\s*:\s*(\d+)/i, /(?:^|\n)\s*Warnings?\s+(\d+)\s*$/im]);
  const fatalMessages = fatalMessagesFromOutput(combined);

  return {
    passed: exitCode === 0 && !timedOut && Number.isInteger(tests) && tests > 0 && Number.isInteger(asserts) && asserts > 0 && failingTests === 0 && errorsReported === 0 && fatalMessages.length === 0,
    counts: { scripts, tests, passing_tests: passingTests, failing_tests: failingTests, pending_tests: pendingTests, asserts, errors: errorsReported, warnings },
    failure: null,
    fatal_patterns: fatalMessages,
    result_source: "stdout_fallback",
    parser_warning: "JUnit XML was not produced; result was extracted from stdout/stderr.",
  };
}

class Semaphore {
  constructor(max) { this.max = max; this.active = 0; this.queue = []; }
  async acquire() {
    if (this.active < this.max) { this.active += 1; return; }
    await new Promise((resolve) => this.queue.push(resolve));
    this.active += 1;
  }
  release() {
    this.active -= 1;
    const next = this.queue.shift();
    if (next) next();
  }
}

export class GutRunner {
  constructor(config, sessionManager, logger) {
    this.config = config;
    this.sessionManager = sessionManager;
    this.logger = logger;
    this.semaphore = new Semaphore(config.gut.maxConcurrentProcesses);
    this.operations = new Map();
  }

  async runDirectory(worktreeName, testDirectory) {
    const safe = validateResPath(testDirectory || this.config.gut.defaultTestDirectory, this.config.gut.allowedTestRoot, "test_directory");
    return await this.#run(worktreeName, { type: "directory", value: safe });
  }

  async runScript(worktreeName, testScript) {
    const safe = validateResPath(testScript, this.config.gut.allowedTestRoot, "test_script");
    return await this.#run(worktreeName, { type: "script", value: safe });
  }

  startDirectory(worktreeName, testDirectory) {
    const safe = validateResPath(testDirectory || this.config.gut.defaultTestDirectory, this.config.gut.allowedTestRoot, "test_directory");
    return this.#startOperation(worktreeName, { type: "directory", value: safe });
  }

  startScript(worktreeName, testScript) {
    const safe = validateResPath(testScript, this.config.gut.allowedTestRoot, "test_script");
    return this.#startOperation(worktreeName, { type: "script", value: safe });
  }

  getOperation(operationId) {
    const operation = this.operations.get(String(operationId || ""));
    if (!operation) return { operation_id: String(operationId || ""), status: "not_found", terminal: true };
    return this.#publicOperation(operation);
  }

  #startOperation(worktreeName, selection) {
    const key = JSON.stringify([worktreeName, selection.type, selection.value]);
    for (const operation of this.operations.values()) {
      if (operation.key === key && (operation.status === "queued" || operation.status === "running")) {
        return { ...this.#publicOperation(operation), reused_existing_operation: true };
      }
    }

    this.#pruneOperations();
    const operation = {
      operation_id: `gut_${randomUUID()}`,
      key,
      worktree_name: worktreeName,
      selection,
      status: "queued",
      terminal: false,
      created_at: new Date().toISOString(),
      started_at: null,
      completed_at: null,
      result: null,
      error: null,
    };
    this.operations.set(operation.operation_id, operation);

    void this.#run(worktreeName, selection, operation).then((result) => {
      operation.status = "completed";
      operation.terminal = true;
      operation.completed_at = new Date().toISOString();
      operation.result = result;
    }).catch(async (error) => {
      operation.status = "failed";
      operation.terminal = true;
      operation.completed_at = new Date().toISOString();
      operation.error = error instanceof Error ? error.message : String(error);
      await this.logger.error("Supervised GUT run failed.", { operation_id: operation.operation_id, worktree: worktreeName, error: operation.error });
    });

    return { ...this.#publicOperation(operation), reused_existing_operation: false, poll_with: "get_gut_run_status" };
  }

  #publicOperation(operation) {
    return {
      operation_id: operation.operation_id,
      worktree_name: operation.worktree_name,
      selection: operation.selection,
      status: operation.status,
      terminal: operation.terminal,
      created_at: operation.created_at,
      started_at: operation.started_at,
      completed_at: operation.completed_at,
      result: operation.result,
      error: operation.error,
    };
  }

  #pruneOperations() {
    const terminal = [...this.operations.values()].filter((operation) => operation.terminal).sort((a, b) => String(a.completed_at || "").localeCompare(String(b.completed_at || "")));
    while (this.operations.size >= 100 && terminal.length > 0) this.operations.delete(terminal.shift().operation_id);
  }

  async #run(worktreeName, selection, operation = null) {
    await this.semaphore.acquire();
    if (operation) {
      operation.status = "running";
      operation.started_at = new Date().toISOString();
    }
    let junitHostPath = null;
    try {
      const session = await this.sessionManager.ensureWorktree(worktreeName, "gut");
      const resultDirectory = path.join(session.host_project_path, ".godot", "gwrm-gut-results");
      await mkdir(resultDirectory, { recursive: true });
      const junitFilename = `gut-${Date.now()}-${randomUUID()}.xml`;
      junitHostPath = path.join(resultDirectory, junitFilename);
      const junitResPath = `res://.godot/gwrm-gut-results/${junitFilename}`;

      const args = [
        ...this.config.godot.executableArgsPrefix,
        "--headless",
        "--path", session.host_project_path,
        "-d",
        "-s", "res://addons/gut/gut_cmdln.gd",
        "-gexit",
        "-gdisable_colors",
        `-gjunit_xml_file=${junitResPath}`,
      ];
      if (selection.type === "script") args.push(`-gtest=${selection.value}`);
      else args.push(`-gdir=${selection.value}`);

      const startedAt = Date.now();
      const result = await new Promise((resolve, reject) => {
        const child = spawn(this.config.paths.godotExecutable, args, {
          // --path selects the project. Keeping cwd outside the worktree avoids Windows directory locks.
          cwd: this.config.appRoot,
          windowsHide: true,
          shell: false,
          env: process.env,
        });
        let stdout = "";
        let stderr = "";
        let timedOut = false;
        let settled = false;
        const finish = (fn) => { if (settled) return; settled = true; clearTimeout(timer); fn(); };
        const timer = setTimeout(async () => {
          timedOut = true;
          await terminateProcessTree(child.pid, this.config, this.logger, session.host_project_path);
        }, this.config.gut.timeoutSeconds * 1000);
        child.stdout.on("data", (chunk) => { stdout += chunk.toString("utf8"); });
        child.stderr.on("data", (chunk) => { stderr += chunk.toString("utf8"); });
        child.once("error", (error) => finish(() => reject(error)));
        child.once("close", (exitCode, signal) => finish(() => resolve({ exitCode, signal, stdout, stderr, timedOut })));
      });

      let parsed;
      let junitXmlError = null;
      try {
        const xml = await readFile(junitHostPath, "utf8");
        parsed = parseGutJunitXml(xml, result.exitCode, result.timedOut);
      } catch (error) {
        junitXmlError = error instanceof Error ? error.message : String(error);
        parsed = parseGutOutput(result.stdout, result.stderr, result.exitCode, result.timedOut);
        parsed.parser_warning = `${parsed.parser_warning} Reason: ${junitXmlError}`;
      }

      const payload = {
        ...parsed,
        exit_code: result.exitCode,
        signal: result.signal,
        timed_out: result.timedOut,
        duration_ms: Date.now() - startedAt,
        worktree_name: worktreeName,
        project_path_container: session.container_project_path,
        project_path_windows: session.host_project_path,
        selection,
        junit_xml_generated: junitXmlError === null,
        junit_xml_error: junitXmlError,
        stdout: limitOutput(result.stdout, this.config.gut.maxOutputCharacters),
        stderr: limitOutput(result.stderr, this.config.gut.maxOutputCharacters),
      };
      await this.logger.info("GUT run completed.", {
        operation_id: operation?.operation_id || null,
        worktree: worktreeName,
        passed: payload.passed,
        counts: payload.counts,
        resultSource: payload.result_source,
      });
      return payload;
    } finally {
      if (junitHostPath) await rm(junitHostPath, { force: true }).catch(() => {});
      this.semaphore.release();
    }
  }
}
