import { spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, rm } from "node:fs/promises";
import path from "node:path";
import { validateResPath } from "./paths.mjs";
import { terminateProcessTree } from "./process-utils.mjs";

function stripAnsi(value) {
  return value.replace(/\u001B\[[0-?]*[ -/]*[@-~]/g, "");
}

function normalizeOutput(value) {
  return stripAnsi(value).replace(/\r\n?/g, "\n");
}

function limitOutput(value, maxCharacters) {
  const clean = normalizeOutput(value).trim();
  if (clean.length <= maxCharacters) return clean;
  return `[saida truncada; ultimos ${maxCharacters} caracteres]\n${clean.slice(-maxCharacters)}`;
}

function numberFrom(text, patterns) {
  for (const pattern of patterns) {
    const match = text.match(pattern);
    if (match) return Number.parseInt(match[1], 10);
  }
  return null;
}

function attributeFrom(tag, name) {
  const match = tag.match(new RegExp(`\\b${name}\\s*=\\s*["'](\\d+)["']`, "i"));
  return match ? Number.parseInt(match[1], 10) : null;
}

function textAttributeFrom(tag, name) {
  const match = tag.match(new RegExp(`\\b${name}\\s*=\\s*["']([^"']*)["']`, "i"));
  return match ? decodeXmlEntities(match[1]) : null;
}

function decodeXmlEntities(value) {
  return value
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&")
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number.parseInt(code, 10)))
    .replace(/&#x([0-9a-f]+);/gi, (_, code) => String.fromCodePoint(Number.parseInt(code, 16)));
}

function tagText(value) {
  return decodeXmlEntities(value.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim());
}

function fatalMessagesFromOutput(combined) {
  // Generic "SCRIPT ERROR" is intentionally excluded. GUT error tracking can
  // capture expected engine/script errors while the related test still passes.
  const fatalPatterns = [
    /Some GUT class_names have not been imported/i,
    /Missing class_names/i,
    /Parse Error/i,
    /Could not resolve class/i,
    /Could not load script/i,
    /No loader found for resource/i,
    /Failed loading (?:scene|script)/i,
    /Cannot open project/i,
    /gut_cmdln\.gd.*(?:not found|could not)/i,
    /No tests found/i,
  ];
  return fatalPatterns
    .filter((pattern) => pattern.test(combined))
    .map((pattern) => pattern.source);
}

/**
 * Parse the JUnit XML generated by GUT's -gjunit_xml_file option.
 * This parser intentionally targets GUT's stable, small JUnit surface and does
 * not require a third-party XML dependency.
 */
export function parseGutJunitXml(xml, exitCode = 0, timedOut = false) {
  const clean = String(xml || "").trim();
  if (!clean.startsWith("<?xml") && !clean.startsWith("<testsuites")) {
    throw new Error("JUnit XML do GUT ausente ou malformado: elemento <testsuites> nao encontrado.");
  }

  const rootTag = clean.match(/<testsuites\b[^>]*>/i)?.[0];
  if (!rootTag) throw new Error("JUnit XML do GUT malformado: elemento <testsuites> nao encontrado.");

  const suiteTags = [...clean.matchAll(/<testsuite\b[^>]*>/gi)].map((match) => match[0]);
  const testcaseBlocks = [...clean.matchAll(/<testcase\b([^>]*)>([\s\S]*?)<\/testcase>|<testcase\b([^>]*)\/>/gi)];
  const failureBlocks = [...clean.matchAll(/<(failure|error)\b([^>]*)>([\s\S]*?)<\/\1>/gi)];

  const sumSuiteAttribute = (name) => suiteTags.reduce((total, tag) => total + (attributeFrom(tag, name) ?? 0), 0);
  const rootTests = attributeFrom(rootTag, "tests");
  const rootFailures = attributeFrom(rootTag, "failures");
  const rootErrors = attributeFrom(rootTag, "errors");
  const rootSkipped = attributeFrom(rootTag, "skipped");

  const tests = rootTests ?? sumSuiteAttribute("tests");
  const failingTests = rootFailures ?? sumSuiteAttribute("failures");
  const errors = rootErrors ?? Math.max(sumSuiteAttribute("errors"), failureBlocks.filter((match) => match[1].toLowerCase() === "error").length);
  const pendingTests = rootSkipped ?? sumSuiteAttribute("skipped");
  const scripts = suiteTags.filter((tag) => (attributeFrom(tag, "tests") ?? 0) > 0).length;

  let asserts = 0;
  let passingFromCases = 0;
  let failingFromCases = 0;
  let pendingFromCases = 0;
  for (const match of testcaseBlocks) {
    const attrs = `<testcase ${match[1] || match[3] || ""}>`;
    asserts += attributeFrom(attrs, "assertions") ?? 0;
    const status = (textAttributeFrom(attrs, "status") || "").toLowerCase();
    if (status === "pass") passingFromCases += 1;
    else if (status === "fail" || status === "error") failingFromCases += 1;
    else if (status === "pending" || status === "skipped") pendingFromCases += 1;
  }

  const effectiveFailing = Math.max(failingTests, failingFromCases);
  const effectivePending = Math.max(pendingTests, pendingFromCases);
  const passingTests = passingFromCases > 0
    ? passingFromCases
    : Math.max(0, tests - effectiveFailing - errors - effectivePending);

  const failures = failureBlocks.map((match) => ({
    type: match[1].toLowerCase(),
    message: textAttributeFrom(`<${match[1]} ${match[2] || ""}>`, "message"),
    details: tagText(match[3] || ""),
  }));

  const passed = exitCode === 0
    && !timedOut
    && tests > 0
    && asserts > 0
    && effectiveFailing === 0
    && errors === 0;

  return {
    passed,
    counts: {
      scripts,
      tests,
      passing_tests: passingTests,
      failing_tests: effectiveFailing,
      pending_tests: effectivePending,
      asserts,
      errors,
      warnings: null,
    },
    failure: failures.length > 0 ? failures : null,
    fatal_patterns: [],
    result_source: "junit_xml",
    parser_warning: null,
  };
}

/**
 * Text parser retained as a compatibility fallback for old GUT versions or
 * infrastructure failures that prevent JUnit XML creation.
 */
export function parseGutOutput(stdout, stderr, exitCode, timedOut = false) {
  const combined = normalizeOutput(`${stdout}\n${stderr}`);
  const scripts = numberFrom(combined, [
    /(?:^|\n)\s*Scripts?\s*:\s*(\d+)/i,
    /(?:^|\n)\s*Scripts?\s+(\d+)\s*$/im,
  ]);
  let tests = numberFrom(combined, [
    /(?:^|\n)\s*Tests?\s*:\s*(\d+)/i,
    /(?:^|\n)\s*Tests?\s+(\d+)\s*$/im,
    /(?:^|\n)\s*Total Tests?\s*:\s*(\d+)/i,
  ]);
  let passingTests = numberFrom(combined, [
    /Passing Tests?\s*:\s*(\d+)/i,
    /Tests? Passed\s*:\s*(\d+)/i,
    /(?:^|\n)\s*Passing\s*:\s*(\d+)/i,
  ]);
  const ratio = combined.match(/\b(\d+)\s*\/\s*(\d+)\s+(?:tests?\s+)?pass(?:ed|ing)\b/i);
  if (ratio) {
    passingTests ??= Number.parseInt(ratio[1], 10);
    tests ??= Number.parseInt(ratio[2], 10);
  }
  const failingTests = numberFrom(combined, [
    /Failing Tests?\s*:\s*(\d+)/i,
    /Tests? Failed\s*:\s*(\d+)/i,
    /(?:^|\n)\s*Failing\s*:\s*(\d+)/i,
    /(?:^|\n)\s*Failures?\s*:\s*(\d+)/i,
  ]) ?? 0;
  const pendingTests = numberFrom(combined, [
    /Pending Tests?\s*:\s*(\d+)/i,
    /(?:^|\n)\s*Pending\s*:\s*(\d+)/i,
    /(?:^|\n)\s*Skipped\s*:\s*(\d+)/i,
  ]) ?? 0;
  const asserts = numberFrom(combined, [
    /(?:^|\n)\s*Asserts?\s*:\s*(\d+)/i,
    /\b(\d+)\s+asserts?\b/i,
  ]);
  const errorsReported = numberFrom(combined, [
    /(?:^|\n)\s*Errors?\s*:\s*(\d+)/i,
    /(?:^|\n)\s*Errors?\s+(\d+)\s*$/im,
  ]) ?? 0;
  const warnings = numberFrom(combined, [
    /(?:^|\n)\s*Warnings?\s*:\s*(\d+)/i,
    /(?:^|\n)\s*Warnings?\s+(\d+)\s*$/im,
  ]);

  const fatalMessages = fatalMessagesFromOutput(combined);
  const passed = exitCode === 0
    && !timedOut
    && Number.isInteger(tests) && tests > 0
    && Number.isInteger(asserts) && asserts > 0
    && failingTests === 0
    && errorsReported === 0
    && fatalMessages.length === 0;

  return {
    passed,
    counts: {
      scripts,
      tests,
      passing_tests: passingTests,
      failing_tests: failingTests,
      pending_tests: pendingTests,
      asserts,
      errors: errorsReported,
      warnings,
    },
    failure: null,
    fatal_patterns: fatalMessages,
    result_source: "stdout_fallback",
    parser_warning: "JUnit XML nao foi produzido; resultado extraido do stdout/stderr.",
  };
}

class Semaphore {
  constructor(max) { this.max = max; this.active = 0; this.queue = []; }
  async acquire() {
    if (this.active < this.max) { this.active += 1; return; }
    await new Promise((resolve) => this.queue.push(resolve));
    this.active += 1;
  }
  release() {
    this.active -= 1;
    const next = this.queue.shift();
    if (next) next();
  }
}

export class GutRunner {
  constructor(config, sessionManager, logger) {
    this.config = config;
    this.sessionManager = sessionManager;
    this.logger = logger;
    this.semaphore = new Semaphore(config.gut.maxConcurrentProcesses);
  }

  async runDirectory(worktreeName, testDirectory) {
    const safe = validateResPath(testDirectory || this.config.gut.defaultTestDirectory, this.config.gut.allowedTestRoot, "test_directory");
    return await this.#run(worktreeName, { type: "directory", value: safe });
  }

  async runScript(worktreeName, testScript) {
    const safe = validateResPath(testScript, this.config.gut.allowedTestRoot, "test_script");
    return await this.#run(worktreeName, { type: "script", value: safe });
  }

  async #run(worktreeName, selection) {
    await this.semaphore.acquire();
    let junitHostPath = null;
    try {
      const session = await this.sessionManager.ensureWorktree(worktreeName, "gut");
      const resultDirectory = path.join(session.host_project_path, ".godot", "gwrm-gut-results");
      await mkdir(resultDirectory, { recursive: true });
      const junitFilename = `gut-${Date.now()}-${randomUUID()}.xml`;
      junitHostPath = path.join(resultDirectory, junitFilename);
      const junitResPath = `res://.godot/gwrm-gut-results/${junitFilename}`;

      const args = [
        ...this.config.godot.executableArgsPrefix,
        "--headless",
        "--path", session.host_project_path,
        "-d",
        "-s", "res://addons/gut/gut_cmdln.gd",
        "-gexit",
        "-gdisable_colors",
        `-gjunit_xml_file=${junitResPath}`,
      ];
      if (selection.type === "script") args.push(`-gtest=${selection.value}`);
      else args.push(`-gdir=${selection.value}`);

      const startedAt = Date.now();
      const result = await new Promise((resolve, reject) => {
        const child = spawn(this.config.paths.godotExecutable, args, {
          // --path seleciona o projeto; manter cwd fora da worktree evita lock no Windows.
          cwd: this.config.appRoot,
          windowsHide: true,
          shell: false,
          env: process.env,
        });
        let stdout = "";
        let stderr = "";
        let timedOut = false;
        let settled = false;
        const finish = (fn) => { if (settled) return; settled = true; clearTimeout(timer); fn(); };
        const timer = setTimeout(async () => {
          timedOut = true;
          await terminateProcessTree(child.pid, this.config, this.logger, session.host_project_path);
        }, this.config.gut.timeoutSeconds * 1000);
        child.stdout.on("data", (chunk) => { stdout += chunk.toString("utf8"); });
        child.stderr.on("data", (chunk) => { stderr += chunk.toString("utf8"); });
        child.once("error", (error) => finish(() => reject(error)));
        child.once("close", (exitCode, signal) => finish(() => resolve({ exitCode, signal, stdout, stderr, timedOut })));
      });

      let parsed;
      let junitXmlError = null;
      try {
        const xml = await readFile(junitHostPath, "utf8");
        parsed = parseGutJunitXml(xml, result.exitCode, result.timedOut);
      } catch (error) {
        junitXmlError = error instanceof Error ? error.message : String(error);
        parsed = parseGutOutput(result.stdout, result.stderr, result.exitCode, result.timedOut);
        parsed.parser_warning = `${parsed.parser_warning} Motivo: ${junitXmlError}`;
      }

      const payload = {
        ...parsed,
        exit_code: result.exitCode,
        signal: result.signal,
        timed_out: result.timedOut,
        duration_ms: Date.now() - startedAt,
        worktree_name: worktreeName,
        project_path_container: session.container_project_path,
        project_path_windows: session.host_project_path,
        selection,
        junit_xml_generated: junitXmlError === null,
        junit_xml_error: junitXmlError,
        stdout: limitOutput(result.stdout, this.config.gut.maxOutputCharacters),
        stderr: limitOutput(result.stderr, this.config.gut.maxOutputCharacters),
      };
      await this.logger.info("Execucao GUT concluida.", {
        worktree: worktreeName,
        passed: payload.passed,
        counts: payload.counts,
        resultSource: payload.result_source,
      });
      return payload;
    } finally {
      if (junitHostPath) await rm(junitHostPath, { force: true }).catch(() => {});
      this.semaphore.release();
    }
  }
}
